openapi: 3.1.0
info:
  title: GPT Access Checker API (Require Key)
  version: 1.0.4
  description: Check access by email. Requires query key (BC_01, GA_01, VD_01).
servers:
  - url: https://gpt-email-api.vercel.app
paths:
  /api/check:
    get:
      summary: Check access (requires key)
      operationId: checkAccessWithKeyV3
      parameters:
        - name: email
          in: query
          required: true
          description: User email to check
          schema:
            type: string
            format: email
        - name: key
          in: query
          required: true
          description: GPT key (e.g. BC_01 for B치o c치o, GA_01 for Gi치o 치n, VD_01 for Video)
          schema:
            type: string
            example: BC_01
      responses:
        "200":
          description: Result
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: boolean
                  gpt:
                    type: string
                  name:
                    type: string
                  expiry:
                    type: string
                    nullable: true
                  daysLeft:
                    type: integer
                    nullable: true
                  match:
                    type: string
                  error:
                    type: string
                    nullable: true
