openapi: 3.1.0
info:
  title: GPT Access Checker API (Header & Query Key)
  version: 1.0.2
  description: |
    Check access by email. Supports:
    - Header `x-gpt-key`
    - Query `key`
    - Query `gpt` & `name`
servers:
  - url: https://gpt-email-api.vercel.app
paths:
  /api/check:
    get:
      summary: Check access (email + optional key)
      operationId: checkAccess
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
          description: User email to check
        - name: x-gpt-key
          in: header
          required: false
          schema:
            type: string
          description: GPT key in request header (priority)
        - name: key
          in: query
          required: false
          schema:
            type: string
          description: GPT key in query string (fallback 1)
        - name: gpt
          in: query
          required: false
          schema:
            type: string
          description: GPT ID in query string (fallback 2)
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: GPT Name in query string (fallback 3)
      responses:
        "200":
          description: Access check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        "400":
          description: Invalid request
        "403":
          description: Access denied
