openapi: 3.1.0
info:
  title: GPT Access Checker API (Auto Key)
  version: 1.0.0
  description: >
    Check access by email. The server auto-assigns GPT ID & Name based on key mapping in Google Sheets.
servers:
  - url: https://gpt-email-api.vercel.app/api/check?email={{user_email}}
paths:
  /api/check:
    get:
      summary: Check user access with auto key
      operationId: checkAccessAutoKey
      parameters:
        - name: email
          in: query
          required: true
          description: User email to check
          schema:
            type: string
            format: email
      responses:
        "200":
          description: Access check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: boolean
                  gpt:
                    type: string
                  name:
                    type: string
                  expiry:
                    type: string
                  daysLeft:
                    type: integer
                  match:
                    type: string
