name: Send Daily Expiry Reminder

on:
  schedule:
    - cron: '0 2 * * *'  # Chạy hàng ngày lúc 2:00 AM UTC (9:00 sáng VN)
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Gửi email nhắc hạn
        run: |
          curl -X GET "https://gpt-email-api.vercel.app/api/send-reminder"
